### ISSUE TITLE
Add support for optional url parameter

### ISSUE THREAD

**Issue by eriktmidtun** [santi/ckeditor-plugin-spotify#2]
Spotify now includes an optional `?si=` url param. Iframes still works without it, but the url validation in this widget does not account for it.
Changing the regex to allow all url params is one option, since there might be added more later. Or just allow an optional `?si`

`/^https?:\/\/open\.spotify\.com\/(album|playlist|track|artist)\/([a-zA-Z0-9]{22})(\?si\=([a-z0-9]{16}))?$/` works on all the links I have tested

**Comment by santi** [comment]
Solved in 8eb526ecd399b15ea87c9ebf65d873f8de18c474
